
var2 = {
# Video Only files
'.webm' : ('WebM', 'Free and libre format created for HTML5 video.'),
'.mkv' : ('Matroska', ''),
'.flv' : ('Flash Video', 'Use of the H.264 and AAC compression formats in the FLV file format has some limitations and authors of Flash Player strongly encourage everyone to embrace the new standard F4V file format.[2] De facto standard for web-based streaming video (over RTMP).'),
'.flv' : ('F4V', 'Replacement for FLV.'),
'.vob' : ('Vob', 'Files in VOB format have .vob filename extension and are typically stored in the VIDEO_TS folder at the root of a DVD.[5] The VOB format is based on the MPEG program stream format.'),
'.ogv' : ('Ogg Video', 'Open source'),
'.ogg' : ('Ogg Video', 'Open source'),
'.drc' : ('Dirac', 'Open source'),
'.mng' : ('Multiple-image Network Graphics', 'Inefficient, not widely used.'),
'.avi' : ('AVI', 'Uses RIFF'),
'.mov' : ('QuickTime File Format', ''),
'.qt' : ('QuickTime File Format', ''),
'.wmv' : ('Windows Media Video', ''),
'.yuv' : ('Raw video format', 'Supports all resolutions, sampling structures, and frame rates'),
'.rm' : ('RealMedia (RM)', 'Made for RealPlayer'),
'.rmvb' : ('RealMedia Variable Bitrate (RMVB)', 'Made for RealPlayer'),
'.asf' : ('Advanced Systems Format (ASF)', ''),
'.mp4' : ('MPEG-1', 'Old, but very widely used due to installed base.'),
'.mp2' : ('MPEG-1', 'Old, but very widely used due to installed base.'),
'.mpeg' : ('MPEG-1', 'Old, but very widely used due to installed base.'),
'.mpe' : ('MPEG-1', 'Old, but very widely used due to installed base.'),
'.mpv' : ('MPEG-1', 'Old, but very widely used due to installed base.'),
'.mpg' : ('MPEG-2 - Video', ''),
'.mpeg' : ('MPEG-2 - Video', ''),
'.m2v' : ('MPEG-2 - Video', ''),
'.m4v' : ('M4V - (file format for videos for iPods and PlayStation Portables developed by Apple)', 'Developed by Apple, used in iTunes. Very similar to MP4 format, but may optionally have DRM.'),
'.svi' : ('SVI', 'Samsung video format for portable players'),
'.3gp' : ('3GPP', 'Common video format for cell phones'),
'.3g2' : ('3GPP2', 'Common video format for cell phones'),
'.mxf' : ('Material Exchange Format (MXF)', ''),
'.roq' : ('ROQ', 'used by Quake 3'),
'.nsv' : ('Nullsoft Streaming Video (NSV)', 'For streaming video content over the Internet'),
}

var1 = {
# Audio Only files
'.3gp' : 'multimedia container format can contain proprietary formats as AMR, AMR-WB or AMR-WB+, but also some open formats',
'.act' : 'ACT is a lossy ADPCM 8 kbit/s compressed audio format recorded by most Chinese MP3 and MP4 players with a recording function, and voice recorders',
'.aiff' : 'standard audio file format used by Apple. It could be considered the Apple equivalent of wav.',
'.aac' : 'the Advanced Audio Coding format is based on the MPEG-2 and MPEG-4 standards. aac files are usually ADTS or ADIF containers.',
'.amr' : 'AMR-NB audio, used primarily for speech.',
'.au' :	'the standard audio file format used by Sun, Unix and Java. The audio in au files can be PCM or compressed with the u-law, a-law or G729 codecs.',
'.awb' : 'AMR-WB audio, used primarily for speech, same as the ITU-T\'s G.722.2 specification.',
'.dct' : 'A variable codec format designed for dictation. It has dictation header information and can be encrypted (as may be required by medical confidentiality laws). A proprietary format of NCH Software.',
'.dss' : 'dss files are an Olympus proprietary format. It is a fairly old and poor codec. Gsm or mp3 are generally preferred where the recorder allows. It allows additional data to be held in the file header.',
'.dvf' : 'a Sony proprietary format for compressed voice files; commonly used by Sony dictation recorders.',
'.flac' : 'File format for the Free Lossless Audio Codec, a lossless compression codec.',
'.gsm' : 'designed for telephony use in Europe, gsm is a very practical format for telephone quality voice. It makes a good compromise between file size and quality. Note that wav files can also be encoded with the gsm codec.',
'.iklax' : 'An iKlax Media proprietary format, the iKlax format is a multi-track digital audio format allowing various actions on musical data, for instance on mixing and volumes arrangements.',
'.ivs' : '3D Solar UK Ltd	A proprietary version with Digital Rights Management developed by 3D Solar UK Ltd for use in music downloaded from their Tronme Music Store and interactive music and video player.',
'.m4a' : 'An audio-only MPEG-4 file, used by Apple for unprotected music downloaded from their iTunes Music Store. Audio within the m4a file is typically encoded with AAC, although lossless ALAC may also be used.',
'.m4p' : 'A version of AAC with proprietary Digital Rights Management developed by Apple for use in music downloaded from their iTunes Music Store.',
'.mmf' : 'a Samsung audio format that is used in ringtones.',
'.mp3' : 'MPEG Layer III Audio. Is the most common sound file format used today.',
'.mpc' : 'Musepack or MPC (formerly known as MPEGplus, MPEG+ or MP+) is an open source lossy audio codec, specifically optimized for transparent compression of stereo audio at bitrates of 160-180 kbit/s.',
'.msv' : 'a Sony proprietary format for Memory Stick compressed voice files.',
'.ogg' : 'a free, open source container format supporting a variety of formats, the most popular of which is the audio format Vorbis. Vorbis offers compression similar to MP3 but is less popular.',
'.oga' : 'a free, open source container format supporting a variety of formats, the most popular of which is the audio format Vorbis. Vorbis offers compression similar to MP3 but is less popular.',
'.opus' : 'a lossy audio compression format developed by the Internet Engineering Task Force (IETF) and made especially suitable for interactive real-time applications over the Internet. As an open format standardised through RFC 6716, a reference implementation is provided under the 3-clause BSD license.',
'.ra' : 'a RealAudio format designed for streaming audio over the Internet. The .ra format allows files to be stored in a self-contained fashion on a computer, with all of the audio data contained inside the file itself.',
'.rm' : 'a RealAudio format designed for streaming audio over the Internet. The .ra format allows files to be stored in a self-contained fashion on a computer, with all of the audio data contained inside the file itself.',
'.raw' : 'a raw file can contain audio in any format but is usually used with PCM audio data. It is rarely used except for technical tests.',
'.sln' : 'Signed Linear PCM format used by Asterisk. Prior to v.10 the standard formats were 16-bit Signed Linear PCM sampled at 8kHz and at 16kHz. With v.10 many more sampling rates were added.',
'.tta' : 'The True Audio, real-time lossless audio codec.',
'.vox' : 'the vox format most commonly uses the Dialogic ADPCM (Adaptive Differential Pulse Code Modulation) codec. Similar to other ADPCM formats, it compresses to 4-bits. Vox format files are similar to wave files except that the vox files contain no information about the file itself so the codec sample rate and number of channels must first be specified in order to play a vox file.',
'.wav' : 'standard audio file container format used mainly in Windows PCs. Commonly used for storing uncompressed (PCM), CD-quality sound files, which means that they can be large in size-around 10 MB per minute. Wave files can also contain data encoded with a variety of (lossy) codecs to reduce the file size (for example the GSM or MP3 formats). Wav files use a RIFF structure.',
'.wma' : 'Windows Media Audio format, created by Microsoft. Designed with Digital Rights Management (DRM) abilities for copy protection.',
'.wv' :	'format for wavpack file http://www.wavpack.com/flash/wavpack.htm',
'.webm' : 'Royalty-free format created for HTML5 video.',
}
