#!/usr/bin/env bash

clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd/include/cli_app_options_creator.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd/include/main.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd/src/cli_app_options_creator.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd/src/main.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd_raw/include/main.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/apps/mmotd_raw/src/main.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/include/assertion.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/include/exception.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/include/precondition.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/include/stack_trace.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/include/throw.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/src/assertion.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/src/exception.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/assertion/src/stack_trace.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/algorithm.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/app_options.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/app_options_creator.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/big_five_macros.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/chrono_io.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/human_size.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/information.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/information_decls.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/information_definitions.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/information_objects.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/informations.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/iostream_error.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/logging.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/mac_address.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/network_device.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/posix_error.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/source_location.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/source_location_common.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/type_traits.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/include/version.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_column.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_column_indexes.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_common.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_frame.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_position_index.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_row.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_row_number_sentinals.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_table.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_template.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/output_template_printer.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/template_column_items.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/template_string.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/template_substring.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/template_substring_range.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/include/template_substrings.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_column.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_column_indexes.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_frame.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_position_index.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_row.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_row_number_sentinals.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_table.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_template.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/output_template_printer.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/template_column_items.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/template_string.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/template_substring.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/template_substring_range.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/results/src/template_substrings.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/app_options.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/app_options_creator.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/information.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/information_decls.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/information_definitions.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/information_objects.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/informations.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/logging.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/mac_address.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/network_device.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/source_location.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/source_location_common.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/src/version.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/include/exception_matcher.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/exception_matcher.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/test_assertion.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/test_exception.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/test_mac_address.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/test_position_index.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/common/test/src/test_template_string.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/boot_time.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/computer_information.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/external_network.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/file_system.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/fortune.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/general.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/http_request.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/information_provider.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/lastlog.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/load_average.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/memory.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/network.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/package_management.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/boot_time.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/lastlog.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/load_average.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/memory.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/network.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/package_management.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/processes.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/swap.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/system_information.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/platform/user_accounting_database.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/processes.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/swap.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/sysctl_defs.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/system_details.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/system_information.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/users_logged_in.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/include/weather_info.h
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/boot_time.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/computer_information.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/external_network.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/file_system.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/fortune.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/general.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/http_request.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/information_provider.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/lastlog.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/load_average.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/memory.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/network.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/package_management.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/boot_time.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/lastlog.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/load_average.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/memory.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/network.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/package_management.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/processes.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/swap.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/system_information.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/darwin/user_accounting_database.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/platform/system_information.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/processes.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/swap.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/system_details.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/system_information.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/users_logged_in.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/src/weather_info.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/lib/test/src/test_information_definitions.cpp
clang-include-fixer --db=yaml -p=build /Users/jasoni/dev/mmotd/test/src/main.cpp
